# Generated by Django 5.1.1 on 2024-09-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="is_checked_out",
            new_name="is_ordered",
        ),
    ]
